name: Drugs
main: Drugs
version: 1.3
author: EqualRights
api-version: 1.15
softdepend:
  - Vault
commands:
  crackhead:
    description: Creates a crackhead.
  drug:
    description: Displays Plugin Info.
